import { describe, expect, it, vi, beforeEach, afterEach } from 'vitest';
import { get } from 'svelte/store';

vi.mock('capacitor-zeroconf', () => ({
  ZeroConf: {
    watch: vi.fn().mockResolvedValue('watch-id'),
    unwatch: vi.fn().mockResolvedValue(undefined),
  },
}));

// pairWithHost()'s crypto (PBKDF2 + AES-256-GCM via Web Crypto) has to
// produce output pairing.rs can actually decrypt, and vice versa -- a
// mismatch in round count, salt construction, or tag string would break
// every real pairing while every *local* check here still passed, since
// both sides would just be internally consistent with themselves. This
// fixture (code/nonce/proof/ciphertext) was generated by pairing.rs's own
// `cargo test -- --nocapture` output and cross-checked once by hand; this
// test locks that cross-language compatibility in as a real regression
// check instead of leaving it as a one-time manual verification.
const FIXTURE = {
  code: '482913',
  nonceB64: 'AQEBAQEBAQEBAQEBAQEBAQ==',
  authProofB64: 'UP+xg803OQQ1jqjCLNJKRNj7DPaZO6Y1wgbaM3/edQA=',
  ivB64: '1/WkfBcsxmtG7Y70',
  ciphertextB64: 'uLLyCpFeNzfWQfLmlmhK0WrSvADA+79xZhkrylURn2442t2DevvEjPmfM4AUEbbbagOmEmQLjIIrVIp7PQxE3MmGiRfUGTo9Gb80zNztWx4BfZA1/Cqmpw==',
  expected: { port: 25984, user: 'offlog', password: 's3cr3t-pw', uuid: 'test-uuid' },
};

const setSyncUrl = vi.fn();
const setSyncCredentials = vi.fn().mockResolvedValue(undefined);
vi.mock('../src/config', () => ({
  setSyncUrl: (...a: unknown[]) => setSyncUrl(...a),
  getSyncUrl: () => '',
  setSyncCredentials: (...a: unknown[]) => setSyncCredentials(...a),
  getPairedHostUuid: () => null,
  setPairedHostUuid: vi.fn(),
}));

const startSync = vi.fn().mockResolvedValue(undefined);
const clearLocalSeedBeforeFirstPair = vi.fn().mockResolvedValue(undefined);
vi.mock('../src/lib/db', () => ({
  startSync: (...a: unknown[]) => startSync(...a),
  clearLocalSeedBeforeFirstPair: (...a: unknown[]) => clearLocalSeedBeforeFirstPair(...a),
  syncState: { status: 'idle', error: null, listeners: new Set() },
}));

import { pairWithHost, scanForHosts, stopScan, isScanning, discoveredHosts, type DiscoveredHost } from '../src/lib/discovery';

const host: DiscoveredHost = { name: 'PC', url: '', uuid: 'test-uuid', address: '127.0.0.1', pairingPort: 5000 };

// The nonce the client generates has to be controllable to reuse the
// fixture above (it's an input to the derivation, not an output) --
// crypto.getRandomValues is stubbed for exactly this one test to return
// the fixture's fixed nonce instead of real randomness.
function stubNonce(bytes: Uint8Array) {
  vi.spyOn(crypto, 'getRandomValues').mockImplementation(((arr: Uint8Array) => {
    arr.set(bytes);
    return arr;
  }) as typeof crypto.getRandomValues);
}

function b64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

beforeEach(() => { vi.clearAllMocks(); vi.restoreAllMocks(); });

describe('pairWithHost', () => {
  it('decrypts a real pairing.rs-produced response and stores the credentials', async () => {
    stubNonce(b64ToBytes(FIXTURE.nonceB64));
    const fetchMock = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({ iv: FIXTURE.ivB64, ciphertext: FIXTURE.ciphertextB64 }),
    });
    vi.stubGlobal('fetch', fetchMock);

    await pairWithHost(host, FIXTURE.code);

    // The request itself must carry the nonce and the correct auth proof
    // -- never the code -- so a passive capture of this exact call has
    // nothing to work with beyond what pairing.rs's own comment already
    // accounts for (offline brute-force of the 6-digit space).
    const [, init] = fetchMock.mock.calls[0];
    const sentBody = JSON.parse(init.body as string);
    expect(sentBody.nonce).toBe(FIXTURE.nonceB64);
    expect(sentBody.proof).toBe(FIXTURE.authProofB64);
    expect(sentBody).not.toHaveProperty('code');
    expect(JSON.stringify(sentBody)).not.toContain(FIXTURE.code);

    expect(setSyncCredentials).toHaveBeenCalledWith(FIXTURE.expected.user, FIXTURE.expected.password);
    expect(setSyncUrl).toHaveBeenCalledWith(`http://${host.address}:${FIXTURE.expected.port}/offlog`);
  });

  it('rejects with the same "incorrect code" message when the code is wrong, not a raw decrypt error', async () => {
    stubNonce(b64ToBytes(FIXTURE.nonceB64));
    // Same server response, but the caller used the wrong code -- its
    // locally-derived key won't match the one pairing.rs actually used,
    // so AES-GCM's own auth-tag check must reject it before any JSON
    // parsing is attempted.
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({ iv: FIXTURE.ivB64, ciphertext: FIXTURE.ciphertextB64 }),
    }));

    await expect(pairWithHost(host, '000000')).rejects.toThrow('Incorrect or expired code.');
    expect(setSyncCredentials).not.toHaveBeenCalled();
  });

  it('surfaces a friendly message when the host is unreachable, not the raw fetch TypeError', async () => {
    vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new TypeError('Failed to fetch')));
    await expect(pairWithHost(host, FIXTURE.code)).rejects.toThrow(/couldn.t reach/i);
  });
});

describe('scanForHosts', () => {
  beforeEach(() => {
    (window as any).Capacitor = { isNativePlatform: () => true };
  });
  afterEach(async () => {
    await stopScan();
    delete (window as any).Capacitor;
  });

  // scanForHosts() awaits a dynamic import('capacitor-zeroconf') before it
  // used to flip isScanning -- a real await point even on a warm module
  // cache, which left Settings' "scan found nothing" state (scanAttempted
  // && !isScanning && zero hosts) briefly true right after the button was
  // pressed. isScanning must already be true the instant the call returns,
  // before that import has any chance to resolve.
  it('sets isScanning synchronously, before the dynamic import resolves', () => {
    discoveredHosts.set([]);
    const promise = scanForHosts();
    expect(get(isScanning)).toBe(true);
    return promise;
  });

  it('clears any hosts left over from a previous scan', () => {
    discoveredHosts.set([{ name: 'Stale', url: '', uuid: 'stale', address: '', pairingPort: null }]);
    const promise = scanForHosts();
    expect(get(discoveredHosts)).toEqual([]);
    return promise;
  });
});
